const mongoose = require('mongoose');
const crypto = require('crypto');

function generateCustomerId() {
  // Example: CUST-MB8N5Z4N-1A2B3C4D
  // - timestamp component keeps it sortable-ish and reduces collision risk
  // - random bytes keep it unpredictable
  const ts = Date.now().toString(36).toUpperCase();
  const rand = crypto.randomBytes(4).toString('hex').toUpperCase();
  return `CUST-${ts}-${rand}`;
}

//Current state of Booking model
const bookingSchema = new mongoose.Schema(
  {
    customerId: {
      // Unique customer/booking reference generated by backend
      type: String,
      required: true,
      default: generateCustomerId,
    },

    providerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Provider',
      default: null,
    },

    serviceType: {
      type: String,
      required: true,
      trim: true,
      enum: ['CLEANING', 'PLUMBING', 'ELECTRICIAN'],
    },

    status: {
      type: String,
      enum: [
        'PENDING',
        'ASSIGNED',
        'IN_PROGRESS',
        'COMPLETED',
        'CANCELLED',
        'FAILED',
      ],
      default: 'PENDING',
      required: true,
    },

    rejectionCount: {
      type: Number,
      default: 0,
      min: 0,
    },

    cancellationReason: {
      type: String,
      default: null,
      trim: true,
    },

    failureReason: {
      type: String,
      default: null,
      trim: true,
    },
  },
  {
    timestamps: true, // createdAt, updatedAt
  }
);

module.exports = mongoose.model('Booking', bookingSchema);
