export const DEFAULT_API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:5000";

export function normalizeBaseUrl(input) {
  const trimmed = String(input || "").trim();
  if (!trimmed) return DEFAULT_API_BASE_URL;
  return trimmed.replace(/\/+$/, "");
}

async function requestJson(baseUrl, path, options = {}) {
  const url = `${normalizeBaseUrl(baseUrl)}${path}`;

  const headers = {
    "Content-Type": "application/json",
    ...(options.headers || {}),
  };

  const res = await fetch(url, {
    ...options,
    headers,
  });

  const contentType = res.headers.get("content-type") || "";
  const isJson = contentType.includes("application/json");
  const payload = isJson ? await res.json() : await res.text();

  if (!res.ok) {
    const message =
      (payload && payload.message) ||
      (typeof payload === "string" ? payload : "Request failed");
    const err = new Error(message);
    err.status = res.status;
    err.payload = payload;
    throw err;
  }

  return payload;
}

export function createApiClient(baseUrl) {
  return {
    health: () => requestJson(baseUrl, "/health", { method: "GET" }),

    listProviders: () => requestJson(baseUrl, "/providers", { method: "GET" }),

    listProviderBookings: (providerId, { status } = {}) => {
      const params = new URLSearchParams();
      if (status) params.set("status", status);
      const qs = params.toString();
      return requestJson(baseUrl, `/providers/${providerId}/bookings${qs ? `?${qs}` : ""}`, {
        method: "GET",
      });
    },

    // customerId is generated by backend; keep it internal.
    createBooking: ({ serviceType } = {}) =>
      requestJson(baseUrl, "/bookings", {
        method: "POST",
        body: JSON.stringify({ serviceType }),
      }),

    listBookings: ({ status, customerId, providerId } = {}) => {
      const params = new URLSearchParams();
      if (status) params.set("status", status);
      if (customerId) params.set("customerId", customerId);
      if (providerId) params.set("providerId", providerId);
      const qs = params.toString();
      return requestJson(baseUrl, `/bookings${qs ? `?${qs}` : ""}`, {
        method: "GET",
      });
    },

    getBooking: (bookingId) =>
      requestJson(baseUrl, `/bookings/${bookingId}`, { method: "GET" }),

    assignProvider: (bookingId, { providerId }) =>
      requestJson(baseUrl, `/bookings/${bookingId}/assign`, {
        method: "POST",
        body: JSON.stringify({ providerId }),
      }),

    respond: (bookingId, { accept, providerId }) =>
      requestJson(baseUrl, `/bookings/${bookingId}/respond`, {
        method: "POST",
        body: JSON.stringify({ accept, providerId }),
      }),

    start: (bookingId) =>
      requestJson(baseUrl, `/bookings/${bookingId}/start`, { method: "POST" }),

    complete: (bookingId) =>
      requestJson(baseUrl, `/bookings/${bookingId}/complete`, {
        method: "POST",
      }),

    cancel: (bookingId, { reason }) =>
      requestJson(baseUrl, `/bookings/${bookingId}/cancel`, {
        method: "POST",
        body: JSON.stringify({ reason }),
      }),

    fail: (bookingId, { reason }) =>
      requestJson(baseUrl, `/bookings/${bookingId}/fail`, {
        method: "POST",
        body: JSON.stringify({ reason }),
      }),

    adminOverride: (bookingId, { status, providerId }) =>
      requestJson(baseUrl, `/admin/bookings/${bookingId}/override`, {
        method: "POST",
        body: JSON.stringify({ status, providerId }),
      }),

    history: (bookingId) =>
      requestJson(baseUrl, `/bookings/${bookingId}/history`, { method: "GET" }),
  };
}
